version: "3.8"

services:

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=camunda
      - MYSQL_USER=camunda
      - MYSQL_PASSWORD=camunda

